server:
  port: 1015
  error:
    include-message: always


cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-arjz3bw9pi-stack-awsebrdsdatabase-ys1t59gg2xor.cp4yowk0q4uo.ap-south-1.rds.amazonaws.com:5432/ebdb
    username: muzaffar
    password: muzaffar
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet


